export enum EmailPriority {
    LOW = 'low',
    MEDIUM = 'medium',
    HIGH = 'high',
    CRITICAL = 'critical'
}

export enum EmailType {
    WELCOME = 'WELCOME',
    PASSWORD_RESET = 'PASSWORD_RESET',
    VACCINATION_REMINDER = 'VACCINATION_REMINDER',
    HEALTH_ALERT = 'HEALTH_ALERT',
    WEEKLY_REPORT = 'WEEKLY_REPORT',
    EMAIL_VERIFICATION = 'EMAIL_VERIFICATION',
    SYSTEM_NOTIFICATION = 'SYSTEM_NOTIFICATION',
    EMERGENCY_ALERT = 'EMERGENCY_ALERT',
    ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
    PROFILE_UPDATED = 'PROFILE_UPDATED'
}