// seeders/01_diseases.seeder.ts
// ============================================================================
// SEEDER — CATÁLOGO DE ENFERMEDADES (34 enfermedades canónicas)
// ============================================================================
// Idempotente: usa findOrCreate con slug como clave única.
// Ejecutar ANTES de aliases, síntomas y relaciones.
// ============================================================================

import Disease, { DiseaseCategory, DiseaseSeverity } from '../models/Disease';
import logger from '../utils/logger';

// ── Helpers ─────────────────────────────────────────────────────────────────

function normalize(text: string): string {
  return text
    .toLowerCase()
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .trim();
}

function slugify(text: string): string {
  return normalize(text)
    .replace(/\s+/g, '-')
    .replace(/[^a-z0-9-]/g, '')
    .replace(/-+/g, '-');
}

// ── Datos ────────────────────────────────────────────────────────────────────

const DISEASES = [
  {
    name: 'Brucelosis',
    description: 'Enfermedad bacteriana crónica causada por Brucella abortus. Principal causa de aborto infeccioso en bovinos y riesgo zoonótico significativo.',
    category: DiseaseCategory.BACTERIAL,
    severity: DiseaseSeverity.HIGH,
    isContagious: true,
    isZoonotic: true,
    defaultQuarantineDays: 30,
    incubationDaysMin: 14,
    incubationDaysMax: 60,
    recommendedAction: 'Aislamiento inmediato, notificación a autoridades sanitarias, prueba de Rosa de Bengala y ELISA. Evaluar sacrificio sanitario del hato positivo.',
    affectedSystems: ['REPRODUCTIVE', 'SYSTEMIC'],
  },
  {
    name: 'Fiebre Aftosa',
    description: 'Enfermedad viral altamente contagiosa causada por el virus de la fiebre aftosa (FMD). Afecta principalmente epitelio oral y podal.',
    category: DiseaseCategory.VIRAL,
    severity: DiseaseSeverity.CRITICAL,
    isContagious: true,
    isZoonotic: false,
    defaultQuarantineDays: 21,
    incubationDaysMin: 2,
    incubationDaysMax: 8,
    recommendedAction: 'Cuarentena estricta, notificación obligatoria a SENASICA. No movilizar animales. Sacrificio sanitario según normativa oficial.',
    affectedSystems: ['DIGESTIVE', 'LOCOMOTOR', 'SYSTEMIC'],
  },
  {
    name: 'Carbunco (Ántrax)',
    description: 'Enfermedad bacteriana aguda causada por Bacillus anthracis. Puede presentarse en forma cutánea, pulmonar o gastrointestinal.',
    category: DiseaseCategory.BACTERIAL,
    severity: DiseaseSeverity.CRITICAL,
    isContagious: true,
    isZoonotic: true,
    defaultQuarantineDays: 30,
    incubationDaysMin: 1,
    incubationDaysMax: 5,
    recommendedAction: 'Aislamiento y notificación inmediata. No realizar necropsia. Incineración de cadáveres. Tratar hato con penicilina y vacunar.',
    affectedSystems: ['SYSTEMIC'],
  },
  {
    name: 'Rabia',
    description: 'Enfermedad viral zoonótica fatal causada por Lyssavirus. En bovinos se presenta principalmente como rabia paralítica transmitida por murciélagos hematófagos.',
    category: DiseaseCategory.VIRAL,
    severity: DiseaseSeverity.CRITICAL,
    isContagious: true,
    isZoonotic: true,
    defaultQuarantineDays: 60,
    incubationDaysMin: 14,
    incubationDaysMax: 90,
    recommendedAction: 'Sacrificio humanitario del animal afectado. Notificación a autoridades. Vacunación antirrábica preventiva del hato en zonas endémicas.',
    affectedSystems: ['NEUROLOGICAL', 'SYSTEMIC'],
  },
  {
    name: 'Pierna Negra',
    description: 'Miopatía necrótica aguda causada por Clostridium chauvoei. Afecta principalmente a bovinos jóvenes (6 meses – 2 años).',
    category: DiseaseCategory.BACTERIAL,
    severity: DiseaseSeverity.CRITICAL,
    isContagious: false,
    isZoonotic: false,
    defaultQuarantineDays: 14,
    incubationDaysMin: 1,
    incubationDaysMax: 5,
    recommendedAction: 'Administrar penicilina en altas dosis. Vacunar hato sobreviviente. Revisar condiciones de pastoreo y manejo de heridas.',
    affectedSystems: ['LOCOMOTOR', 'SYSTEMIC'],
  },
  {
    name: 'Rinotraqueítis Infecciosa Bovina (IBR)',
    description: 'Enfermedad viral respiratoria y reproductiva causada por el Herpesvirus bovino tipo 1 (BoHV-1).',
    category: DiseaseCategory.VIRAL,
    severity: DiseaseSeverity.HIGH,
    isContagious: true,
    isZoonotic: false,
    defaultQuarantineDays: 14,
    incubationDaysMin: 2,
    incubationDaysMax: 6,
    recommendedAction: 'Aislamiento de animales enfermos. Tratamiento sintomático y antibióticos para prevenir infecciones secundarias. Vacunación del hato.',
    affectedSystems: ['RESPIRATORY', 'REPRODUCTIVE'],
  },
  {
    name: 'Diarrea Viral Bovina (BVD)',
    description: 'Enfermedad viral causada por el Pestivirus bovino. Puede causar inmunosupresión, diarrea, lesiones en mucosas y abortos.',
    category: DiseaseCategory.VIRAL,
    severity: DiseaseSeverity.HIGH,
    isContagious: true,
    isZoonotic: false,
    defaultQuarantineDays: 14,
    incubationDaysMin: 5,
    incubationDaysMax: 7,
    recommendedAction: 'Identificar y eliminar animales persistentemente infectados (PI). Vacunación del hato. Manejo higiénico de instalaciones.',
    affectedSystems: ['DIGESTIVE', 'RESPIRATORY', 'REPRODUCTIVE', 'SYSTEMIC'],
  },
  {
    name: 'Leptospirosis',
    description: 'Enfermedad bacteriana causada por Leptospira spp. Se transmite principalmente por agua y suelo contaminados. Causa abortos y hemoglobinuria.',
    category: DiseaseCategory.BACTERIAL,
    severity: DiseaseSeverity.HIGH,
    isContagious: true,
    isZoonotic: true,
    defaultQuarantineDays: 21,
    incubationDaysMin: 5,
    incubationDaysMax: 14,
    recommendedAction: 'Tratamiento con estreptomicina u oxitetraciclina. Controlar fuentes de agua. Vacunación bivalente o pentavalente del hato.',
    affectedSystems: ['REPRODUCTIVE', 'SYSTEMIC'],
  },
  {
    name: 'Tuberculosis Bovina',
    description: 'Enfermedad bacteriana crónica causada por Mycobacterium bovis. Afecta principalmente el sistema respiratorio y es de notificación obligatoria.',
    category: DiseaseCategory.BACTERIAL,
    severity: DiseaseSeverity.HIGH,
    isContagious: true,
    isZoonotic: true,
    defaultQuarantineDays: 60,
    incubationDaysMin: 42,
    incubationDaysMax: 180,
    recommendedAction: 'Prueba de tuberculina. Sacrificio sanitario de reactores positivos. Notificación a SENASICA. Programa oficial de control.',
    affectedSystems: ['RESPIRATORY', 'SYSTEMIC'],
  },
  {
    name: 'Tétanos',
    description: 'Enfermedad causada por las toxinas de Clostridium tetani. Se presenta tras contaminación de heridas con esporas del suelo.',
    category: DiseaseCategory.BACTERIAL,
    severity: DiseaseSeverity.CRITICAL,
    isContagious: false,
    isZoonotic: false,
    defaultQuarantineDays: null,
    incubationDaysMin: 3,
    incubationDaysMax: 21,
    recommendedAction: 'Administrar antitoxina tetánica y penicilina. Limpiar y desinfectar heridas. Vacunación preventiva del hato con toxoide tetánico.',
    affectedSystems: ['NEUROLOGICAL', 'LOCOMOTOR'],
  },
  {
    name: 'Parainfluenza Bovina',
    description: 'Infección respiratoria viral causada por el Virus Parainfluenza tipo 3 (PIV-3). Actúa frecuentemente como cofactor del complejo respiratorio bovino.',
    category: DiseaseCategory.VIRAL,
    severity: DiseaseSeverity.MODERATE,
    isContagious: true,
    isZoonotic: false,
    defaultQuarantineDays: 7,
    incubationDaysMin: 3,
    incubationDaysMax: 7,
    recommendedAction: 'Tratamiento sintomático. Antibióticos para prevenir infecciones bacterianas secundarias. Vacunación incluida en polivalentes respiratorias.',
    affectedSystems: ['RESPIRATORY'],
  },
  {
    name: 'Síncitial Respiratorio Bovino (RSV)',
    description: 'Enfermedad respiratoria viral causada por el Pneumovirus bovino. Principal causa de bronconeumonía grave en terneros.',
    category: DiseaseCategory.VIRAL,
    severity: DiseaseSeverity.MODERATE,
    isContagious: true,
    isZoonotic: false,
    defaultQuarantineDays: 7,
    incubationDaysMin: 3,
    incubationDaysMax: 5,
    recommendedAction: 'Tratamiento sintomático con broncodilatadores. Antibióticos para prevenir sobreinfección bacteriana. Vacunación preventiva.',
    affectedSystems: ['RESPIRATORY'],
  },
  {
    name: 'Mastitis',
    description: 'Inflamación de la glándula mamaria causada principalmente por Staphylococcus aureus, Streptococcus agalactiae y coliformes. Principal pérdida económica en bovinos lecheros.',
    category: DiseaseCategory.BACTERIAL,
    severity: DiseaseSeverity.MODERATE,
    isContagious: false,
    isZoonotic: false,
    defaultQuarantineDays: 0,
    incubationDaysMin: 1,
    incubationDaysMax: 3,
    recommendedAction: 'Antibióticoterapia intramamaria según antibiograma. Ordeño de cuartos afectados. Tiempo de retiro de leche. Sellado de pezones post-ordeño.',
    affectedSystems: ['REPRODUCTIVE'],
  },
  {
    name: 'Cisticercosis Bovina',
    description: 'Infestación por larvas de Taenia saginata (Cysticercus bovis). El bovino actúa como hospedero intermediario. Riesgo zoonótico por consumo de carne mal cocida.',
    category: DiseaseCategory.PARASITIC,
    severity: DiseaseSeverity.MODERATE,
    isContagious: false,
    isZoonotic: true,
    defaultQuarantineDays: 0,
    incubationDaysMin: 60,
    incubationDaysMax: 90,
    recommendedAction: 'No existe tratamiento eficaz en bovinos. Decomiso en rastro. Control sanitario de aguas residuales y manejo de heces humanas en praderas.',
    affectedSystems: ['NEUROLOGICAL', 'LOCOMOTOR', 'SYSTEMIC'],
  },
  {
    name: 'Encefalopatía Espongiforme Bovina (EEB)',
    description: 'Enfermedad neurológica degenerativa fatal causada por priones. Conocida popularmente como "mal de las vacas locas". Notificación obligatoria internacional.',
    category: DiseaseCategory.OTHER,
    severity: DiseaseSeverity.CRITICAL,
    isContagious: false,
    isZoonotic: true,
    defaultQuarantineDays: null,
    incubationDaysMin: 730,
    incubationDaysMax: 1825,
    recommendedAction: 'Sacrificio inmediato y notificación a OIE/SENASICA. Prohibición de harinas de carne y hueso. Seguimiento epidemiológico del hato.',
    affectedSystems: ['NEUROLOGICAL'],
  },
  {
    name: 'Anaplasmosis Bovina',
    description: 'Enfermedad rickettsial causada por Anaplasma marginale, transmitida principalmente por garrapatas del género Boophilus. Causa anemia hemolítica severa.',
    category: DiseaseCategory.PARASITIC,
    severity: DiseaseSeverity.HIGH,
    isContagious: false,
    isZoonotic: false,
    defaultQuarantineDays: 14,
    incubationDaysMin: 7,
    incubationDaysMax: 30,
    recommendedAction: 'Oxitetraciclina de larga acción. Control de garrapatas con acaricidas. Vacunación en zonas endémicas.',
    affectedSystems: ['SYSTEMIC'],
  },
  {
    name: 'Babesiosis Bovina',
    description: 'Enfermedad parasitaria causada por Babesia bovis y B. bigemina, transmitida por garrapatas. Produce hemólisis intravascular y hemoglobinuria.',
    category: DiseaseCategory.PARASITIC,
    severity: DiseaseSeverity.HIGH,
    isContagious: false,
    isZoonotic: false,
    defaultQuarantineDays: 14,
    incubationDaysMin: 7,
    incubationDaysMax: 21,
    recommendedAction: 'Imidocarb o diminazene como tratamiento específico. Control de garrapatas. Vacunación con cepas atenuadas en zonas endémicas.',
    affectedSystems: ['SYSTEMIC'],
  },
  {
    name: 'Queratoconjuntivitis Infecciosa',
    description: 'Enfermedad ocular contagiosa causada principalmente por Moraxella bovis. Produce opacidad corneal y úlceras. Afecta principalmente en épocas de alta radiación solar.',
    category: DiseaseCategory.BACTERIAL,
    severity: DiseaseSeverity.MODERATE,
    isContagious: true,
    isZoonotic: false,
    defaultQuarantineDays: 7,
    incubationDaysMin: 2,
    incubationDaysMax: 5,
    recommendedAction: 'Antibióticos oculares (oxitetraciclina) y sistémicos. Proteger ojos de luz solar. Controlar moscas vectoras.',
    affectedSystems: ['DERMATOLOGICAL'],
  },
  {
    name: 'Neumonía Bovina',
    description: 'Infección del parénquima pulmonar de etiología multifactorial (Mannheimia, Pasteurella, Histophilus). Principal causa de muerte en bovinos jóvenes.',
    category: DiseaseCategory.BACTERIAL,
    severity: DiseaseSeverity.HIGH,
    isContagious: true,
    isZoonotic: false,
    defaultQuarantineDays: 14,
    incubationDaysMin: 3,
    incubationDaysMax: 7,
    recommendedAction: 'Antibióticos de amplio espectro (florfenicol, tulatiromicina). Antiinflamatorios AINEs. Soporte nutricional e hídrico.',
    affectedSystems: ['RESPIRATORY', 'SYSTEMIC'],
  },
  {
    name: 'Diarrea Neonatal Bovina',
    description: 'Síndrome diarreico agudo en becerros menores de 30 días causado por E. coli, rotavirus, coronavirus o Cryptosporidium. Principal causa de mortalidad neonatal.',
    category: DiseaseCategory.BACTERIAL,
    severity: DiseaseSeverity.HIGH,
    isContagious: true,
    isZoonotic: false,
    defaultQuarantineDays: 14,
    incubationDaysMin: 1,
    incubationDaysMax: 5,
    recommendedAction: 'Rehidratación oral o IV. Antibióticos para control bacteriano. Calostro en primeras 6 horas de vida como prevención. Vacunación de vacas gestantes.',
    affectedSystems: ['DIGESTIVE', 'SYSTEMIC'],
  },
  {
    name: 'Salmonelosis Bovina',
    description: 'Gastroenteritis bacteriana causada por Salmonella Dublin y S. Typhimurium. Produce diarrea hemorrágica, septicemia y abortos. Riesgo zoonótico.',
    category: DiseaseCategory.BACTERIAL,
    severity: DiseaseSeverity.HIGH,
    isContagious: true,
    isZoonotic: true,
    defaultQuarantineDays: 21,
    incubationDaysMin: 1,
    incubationDaysMax: 3,
    recommendedAction: 'Fluidoterapia intensiva. Antibióticos según antibiograma. Aislamiento estricto. Revisión de agua, alimentos y manejo sanitario.',
    affectedSystems: ['DIGESTIVE', 'SYSTEMIC'],
  },
  {
    name: 'Metritis / Endometritis',
    description: 'Infección uterina postparto causada por contaminación bacteriana (E. coli, Trueperella pyogenes). Causa infertilidad y pérdidas reproductivas.',
    category: DiseaseCategory.BACTERIAL,
    severity: DiseaseSeverity.MODERATE,
    isContagious: false,
    isZoonotic: false,
    defaultQuarantineDays: null,
    incubationDaysMin: 1,
    incubationDaysMax: 10,
    recommendedAction: 'Oxitocina para drenaje uterino. Antibióticos sistémicos e intrauterinos. Revisión de condición corporal y manejo del parto.',
    affectedSystems: ['REPRODUCTIVE'],
  },
  {
    name: 'Listeriosis Bovina',
    description: 'Enfermedad bacteriana causada por Listeria monocytogenes. Se presenta como encefalitis, aborto o septicemia. Asociada a ensilaje mal fermentado.',
    category: DiseaseCategory.BACTERIAL,
    severity: DiseaseSeverity.HIGH,
    isContagious: false,
    isZoonotic: true,
    defaultQuarantineDays: 30,
    incubationDaysMin: 14,
    incubationDaysMax: 60,
    recommendedAction: 'Penicilina en dosis altas. Revisión y eliminación de ensilajes sospechosos. Separar animales afectados.',
    affectedSystems: ['NEUROLOGICAL', 'SYSTEMIC'],
  },
  {
    name: 'Actinobacilosis',
    description: 'Infección crónica granulomatosa en tejidos blandos causada por Actinobacillus lignieresii. Afecta lengua (lengua de madera) y ganglios linfáticos.',
    category: DiseaseCategory.BACTERIAL,
    severity: DiseaseSeverity.MODERATE,
    isContagious: false,
    isZoonotic: false,
    defaultQuarantineDays: null,
    incubationDaysMin: null,
    incubationDaysMax: null,
    recommendedAction: 'Yoduro de potasio oral o yoduro de sodio IV. Penicilina sistémica. Cirugía de abscesos en casos graves.',
    affectedSystems: ['DIGESTIVE', 'LOCOMOTOR'],
  },
  {
    name: 'Actinomicosis',
    description: 'Infección ósea crónica granulomatosa causada por Actinomyces bovis. Afecta principalmente la mandíbula (quijada esponjosa). Evolución lenta y progresiva.',
    category: DiseaseCategory.BACTERIAL,
    severity: DiseaseSeverity.MODERATE,
    isContagious: false,
    isZoonotic: false,
    defaultQuarantineDays: null,
    incubationDaysMin: null,
    incubationDaysMax: null,
    recommendedAction: 'Yoduro de potasio a largo plazo. Penicilina. Cirugía de desbridamiento. Pronóstico reservado en casos avanzados.',
    affectedSystems: ['LOCOMOTOR'],
  },
  {
    name: 'Hipocalcemia (Fiebre de Leche)',
    description: 'Trastorno metabólico por descenso brusco del calcio sérico al inicio de la lactación. Afecta principalmente vacas lecheras de alta producción en el periparto.',
    category: DiseaseCategory.METABOLIC,
    severity: DiseaseSeverity.HIGH,
    isContagious: false,
    isZoonotic: false,
    defaultQuarantineDays: null,
    incubationDaysMin: null,
    incubationDaysMax: null,
    recommendedAction: 'Gluconato de calcio IV (solución al 23%) lenta. Manejo de la dieta prepartum con cationes-aniones. Suplementación con vitamina D3.',
    affectedSystems: ['NEUROLOGICAL', 'LOCOMOTOR', 'SYSTEMIC'],
  },
  {
    name: 'Cetosis Bovina',
    description: 'Trastorno metabólico por balance energético negativo en vacas de alta producción durante las primeras semanas de lactación. Acumulación de cuerpos cetónicos.',
    category: DiseaseCategory.METABOLIC,
    severity: DiseaseSeverity.MODERATE,
    isContagious: false,
    isZoonotic: false,
    defaultQuarantineDays: null,
    incubationDaysMin: null,
    incubationDaysMax: null,
    recommendedAction: 'Glucosa IV (500 mL al 50%). Propilenglicol oral. Corticoides para estimular gluconeogénesis. Ajuste de ración energética.',
    affectedSystems: ['SYSTEMIC', 'NEUROLOGICAL'],
  },
  {
    name: 'Dermatofitosis (Tiña)',
    description: 'Infección micótica superficial de la piel causada por Trichophyton verrucosum. Produce lesiones circulares alopécicas con costras. Contagiosa entre animales y zoonótica.',
    category: DiseaseCategory.FUNGAL,
    severity: DiseaseSeverity.LOW,
    isContagious: true,
    isZoonotic: true,
    defaultQuarantineDays: 21,
    incubationDaysMin: 4,
    incubationDaysMax: 14,
    recommendedAction: 'Antifúngicos tópicos (enilconazol, natamicina). Aislamiento del animal. Desinfección de instalaciones. Tratamiento de todos los animales en contacto.',
    affectedSystems: ['DERMATOLOGICAL'],
  },
  {
    name: 'Fotosensibilización',
    description: 'Reacción inflamatoria de la piel expuesta a la luz solar, secundaria a ingestión de plantas fotosensibilizantes o disfunción hepática. Afecta áreas despigmentadas.',
    category: DiseaseCategory.OTHER,
    severity: DiseaseSeverity.MODERATE,
    isContagious: false,
    isZoonotic: false,
    defaultQuarantineDays: null,
    incubationDaysMin: null,
    incubationDaysMax: null,
    recommendedAction: 'Retirar los animales de la fuente (planta o alimento). Proteger de la luz solar. Corticoides y antihistamínicos. Tratar causa subyacente hepática si aplica.',
    affectedSystems: ['DERMATOLOGICAL', 'SYSTEMIC'],
  },
  {
    name: 'Timpanismo (Meteorismo)',
    description: 'Acumulación excesiva de gas en el rumen que impide su eructación. Puede ser espumoso (por leguminosas) o libre (obstrucción esofágica). Emergencia veterinaria.',
    category: DiseaseCategory.OTHER,
    severity: DiseaseSeverity.HIGH,
    isContagious: false,
    isZoonotic: false,
    defaultQuarantineDays: null,
    incubationDaysMin: null,
    incubationDaysMax: null,
    recommendedAction: 'Trocarización del rumen en emergencia. Aceites minerales o antiespumantes. Sonda nasogástrica para liberar gas. Restricción de pastoreo en leguminosas.',
    affectedSystems: ['DIGESTIVE'],
  },
  {
    name: 'Pasteurelosis Bovina',
    description: 'Enfermedad respiratoria y septicémica causada por Mannheimia haemolytica y Pasteurella multocida. Componente clave del Complejo Respiratorio Bovino.',
    category: DiseaseCategory.BACTERIAL,
    severity: DiseaseSeverity.HIGH,
    isContagious: true,
    isZoonotic: false,
    defaultQuarantineDays: 14,
    incubationDaysMin: 1,
    incubationDaysMax: 5,
    recommendedAction: 'Antibióticos de amplio espectro (florfenicol, tulatiromicina, enrofloxacina). AINEs. Aislamiento de animales febriles. Vacunación del hato.',
    affectedSystems: ['RESPIRATORY', 'SYSTEMIC'],
  },
  {
    name: 'Clostridiosis (Enterotoxemia)',
    description: 'Enfermedad aguda y fatal causada por toxinas de Clostridium perfringens tipos A, B, C y D. Se presenta principalmente en animales jóvenes bien alimentados.',
    category: DiseaseCategory.BACTERIAL,
    severity: DiseaseSeverity.CRITICAL,
    isContagious: false,
    isZoonotic: false,
    defaultQuarantineDays: 0,
    incubationDaysMin: 1,
    incubationDaysMax: 3,
    recommendedAction: 'Suero antitoxínico de emergencia. Penicilina. Vacunación polivalente de todo el hato. Revisión de manejo alimentario.',
    affectedSystems: ['DIGESTIVE', 'SYSTEMIC'],
  },
  {
    name: 'Fiebre de Embarque',
    description: 'Síndrome respiratorio multifactorial desencadenado por el estrés del transporte. Causado por combinación de virus (IBR, PI3, BRSV) y bacterias (Mannheimia, Pasteurella).',
    category: DiseaseCategory.VIRAL,
    severity: DiseaseSeverity.HIGH,
    isContagious: true,
    isZoonotic: false,
    defaultQuarantineDays: 14,
    incubationDaysMin: 2,
    incubationDaysMax: 5,
    recommendedAction: 'Metafilaxis antibiótica al ingreso. AINEs. Vitaminas A, E y selenio. Reducir densidad de animales y estrés durante transporte.',
    affectedSystems: ['RESPIRATORY', 'SYSTEMIC'],
  },
  {
    name: 'Campilobacteriosis Genital Bovina',
    description: 'Enfermedad reproductiva causada por Campylobacter fetus subsp. venerealis. Se transmite por monta natural y causa infertilidad temprana y abortos.',
    category: DiseaseCategory.BACTERIAL,
    severity: DiseaseSeverity.MODERATE,
    isContagious: true,
    isZoonotic: true,
    defaultQuarantineDays: 30,
    incubationDaysMin: 1,
    incubationDaysMax: 7,
    recommendedAction: 'Inseminación artificial en reemplazo de monta natural. Vacunación del hato con bacterinas. Tratamiento con estreptomicina en toros afectados.',
    affectedSystems: ['REPRODUCTIVE'],
  },

  // ── Enfermedades añadidas para completar el mapeo de vacunación ──────────────
  {
    name: 'Tricomoniasis Bovina',
    description: 'Enfermedad reproductiva venérea causada por el protozoario Tritrichomonas foetus. Se transmite por monta natural y provoca infertilidad, muerte embrionaria temprana y piómetra.',
    category: DiseaseCategory.PARASITIC,
    severity: DiseaseSeverity.MODERATE,
    isContagious: true,
    isZoonotic: false,
    defaultQuarantineDays: 30,
    incubationDaysMin: 14,
    incubationDaysMax: 30,
    recommendedAction: 'Reemplazar monta natural por inseminación artificial. Descartar toros positivos. Vacunación del hato y descanso sexual de las hembras.',
    affectedSystems: ['REPRODUCTIVE'],
  },
  {
    name: 'Pododermatitis Infecciosa (Foot Rot)',
    description: 'Infección necrótica del tejido interdigital causada por Fusobacterium necrophorum y Dichelobacter nodosus. Produce cojera aguda, inflamación y mal olor característico.',
    category: DiseaseCategory.BACTERIAL,
    severity: DiseaseSeverity.MODERATE,
    isContagious: true,
    isZoonotic: false,
    defaultQuarantineDays: 7,
    incubationDaysMin: 2,
    incubationDaysMax: 7,
    recommendedAction: 'Limpieza y desbridamiento del espacio interdigital. Antibióticos sistémicos. Pediluvios con sulfato de cobre o zinc. Vacunación en hatos con alta incidencia.',
    affectedSystems: ['LOCOMOTOR'],
  },
  {
    name: 'Dermatosis Nodular Contagiosa',
    description: 'Enfermedad viral (Capripoxvirus / Lumpy Skin Disease) que produce nódulos cutáneos generalizados, fiebre y caída en producción. Transmitida por insectos vectores. Notificación obligatoria.',
    category: DiseaseCategory.VIRAL,
    severity: DiseaseSeverity.HIGH,
    isContagious: true,
    isZoonotic: false,
    defaultQuarantineDays: 28,
    incubationDaysMin: 4,
    incubationDaysMax: 14,
    recommendedAction: 'Aislamiento y notificación oficial. Control de vectores (moscas, mosquitos, garrapatas). Vacunación preventiva del hato. Tratamiento sintomático de lesiones.',
    affectedSystems: ['DERMATOLOGICAL', 'SYSTEMIC'],
  },
  {
    name: 'Lengua Azul',
    description: 'Enfermedad viral (Orbivirus) transmitida por mosquitos del género Culicoides. Produce fiebre, edema facial, cianosis lingual y lesiones podales. Afecta principalmente a ovinos pero también bovinos.',
    category: DiseaseCategory.VIRAL,
    severity: DiseaseSeverity.HIGH,
    isContagious: true,
    isZoonotic: false,
    defaultQuarantineDays: 21,
    incubationDaysMin: 5,
    incubationDaysMax: 10,
    recommendedAction: 'Control de vectores Culicoides. Vacunación con serotipo regional. Tratamiento sintomático y de soporte. Notificación según normativa.',
    affectedSystems: ['DIGESTIVE', 'LOCOMOTOR', 'SYSTEMIC'],
  },
  {
    name: 'Teileriosis Bovina',
    description: 'Enfermedad parasitaria causada por protozoarios del género Theileria, transmitida por garrapatas. Produce fiebre, anemia, linfadenopatía y alta mortalidad en zonas endémicas.',
    category: DiseaseCategory.PARASITIC,
    severity: DiseaseSeverity.HIGH,
    isContagious: false,
    isZoonotic: false,
    defaultQuarantineDays: 14,
    incubationDaysMin: 8,
    incubationDaysMax: 25,
    recommendedAction: 'Buparvacuona como tratamiento específico. Control estricto de garrapatas con acaricidas. Vacunación en regiones endémicas.',
    affectedSystems: ['SYSTEMIC'],
  },
  {
    name: 'Paratuberculosis (Enfermedad de Johne)',
    description: 'Enteritis crónica granulomatosa causada por Mycobacterium avium subsp. paratuberculosis. Produce diarrea crónica intratable, pérdida de peso progresiva y caída en producción. Sin cura.',
    category: DiseaseCategory.BACTERIAL,
    severity: DiseaseSeverity.HIGH,
    isContagious: true,
    isZoonotic: false,
    defaultQuarantineDays: 30,
    incubationDaysMin: 730,
    incubationDaysMax: 1825,
    recommendedAction: 'No existe tratamiento curativo. Identificar y eliminar animales positivos. Manejo higiénico del calostro y becerros. Vacunación donde esté autorizada.',
    affectedSystems: ['DIGESTIVE', 'SYSTEMIC'],
  },
  {
    name: 'Edema Maligno',
    description: 'Mionecrosis clostridial aguda causada por Clostridium septicum (y otros) tras contaminación de heridas. Produce edema gaseoso, fiebre alta y toxemia fatal. Componente de las polivalentes clostridiales.',
    category: DiseaseCategory.BACTERIAL,
    severity: DiseaseSeverity.CRITICAL,
    isContagious: false,
    isZoonotic: false,
    defaultQuarantineDays: 0,
    incubationDaysMin: 1,
    incubationDaysMax: 5,
    recommendedAction: 'Penicilina en altas dosis y desbridamiento quirúrgico temprano. Vacunación polivalente clostridial del hato. Manejo aséptico de heridas y partos.',
    affectedSystems: ['LOCOMOTOR', 'SYSTEMIC'],
  },
  {
    name: 'Hemoglobinuria Bacilar',
    description: 'Enfermedad clostridial aguda causada por Clostridium haemolyticum. Produce hemólisis intravascular, hemoglobinuria, ictericia y muerte súbita. Asociada a daño hepático por Fasciola.',
    category: DiseaseCategory.BACTERIAL,
    severity: DiseaseSeverity.CRITICAL,
    isContagious: false,
    isZoonotic: false,
    defaultQuarantineDays: 0,
    incubationDaysMin: 1,
    incubationDaysMax: 7,
    recommendedAction: 'Penicilina y transfusión sanguínea de soporte. Control de Fasciola hepatica. Vacunación polivalente clostridial en zonas endémicas.',
    affectedSystems: ['SYSTEMIC'],
  },
  {
    name: 'Hepatitis Necrótica Infecciosa',
    description: 'Enfermedad clostridial causada por Clostridium novyi tipo B. Produce necrosis hepática aguda y muerte súbita, frecuentemente asociada a migración de Fasciola. Componente de las polivalentes clostridiales.',
    category: DiseaseCategory.BACTERIAL,
    severity: DiseaseSeverity.CRITICAL,
    isContagious: false,
    isZoonotic: false,
    defaultQuarantineDays: 0,
    incubationDaysMin: 1,
    incubationDaysMax: 7,
    recommendedAction: 'Pronóstico reservado por curso fulminante. Control de Fasciola hepatica. Vacunación polivalente clostridial preventiva del hato.',
    affectedSystems: ['SYSTEMIC'],
  },
];

// ── Seeder ───────────────────────────────────────────────────────────────────

const CONTEXT = '01_diseases.seeder';

export async function seedDiseases(): Promise<void> {
  logger.info(`Iniciando seeder de enfermedades (${DISEASES.length} registros)`, CONTEXT);

  let created = 0;
  let skipped = 0;

  for (const d of DISEASES) {
    const slug = slugify(d.name);
    const normalizedName = normalize(d.name);

    const [, wasCreated] = await Disease.findOrCreate({
      where: { slug },
      defaults: {
        name: d.name,
        normalizedName,
        slug,
        description: d.description,
        category: d.category,
        severity: d.severity,
        isContagious: d.isContagious,
        isZoonotic: d.isZoonotic,
        defaultQuarantineDays: d.defaultQuarantineDays ?? undefined,
        incubationDaysMin: d.incubationDaysMin ?? undefined,
        incubationDaysMax: d.incubationDaysMax ?? undefined,
        recommendedAction: d.recommendedAction,
        affectedSystems: d.affectedSystems,
        isActive: true,
      },
    });

    if (wasCreated) created++;
    else skipped++;
  }

  logger.info(`Enfermedades — creadas: ${created}, ya existían: ${skipped}`, CONTEXT);
}
